name: 'Yaspeller'
description: 'Writing take time, correction should not'
inputs:
  ext:
    description: "file extensions, e.g. '.md,.html'"
    required: true
  dir:
    description: "Base directory"
    default: "."
  dictionary:
    description: "Path to dictionary"
outputs:
  output: # id of output
    description: "Suggestion"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.ext }}
    - ${{ inputs.dir }}
    - ${{ inputs.directory }}
