name: 'Yaspeller'
description: 'Writing take time, correction should not'
inputs:
  filepath:
    description: "Glob syntax for files"
    required: true
  dir:
    description: "Base directory"
    default: "."
outputs:
  output: # id of output
    description: "Suggestion"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.filepath }}
    - ${{ inputs.dir }}
