name: "Github action for Yaspeller"
description: "write more 📝, care less 😎."
icon: "alert-triangle"
color: "red"
inputs:
  ext:
    description: "file extensions, e.g. '.md,.html'"
    required: true
  dir:
    description: "Base directory"
    default: "."
  dictionary:
    description: "Path to dictionary"
    default: ""
outputs:
  output: # id of output
    description: "Suggestion"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.ext }}
    - ${{ inputs.dir }}
    - ${{ inputs.dictionary }}