on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Unitests
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test Bad file
        uses: ./ # Uses an action in the root directory
        id: current-action
        with:
          ext: ".md"
          dir: "./test-files/bad"