on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Unitests
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test Good File
        uses: ./ # Uses an action in the root directory
        id: current-action-test-good-file
        with:
          ext: ".md"
          dir: "./test-files/good"
      - name: Test Good File with Dict
        uses: ./ # Uses an action in the root directory
        id: current-action-test-good-file-with-dict
        with:
          ext: ".md"
          dir: "./test-files/with-dict"
          dictionary: ".github/workflows/dict.json"
      - name: Test Bad file
        uses: ./ # Uses an action in the root directory
        id: current-action-test-bad-file
        with:
          ext: ".md"
          dir: "./test-files/bad"