on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: "Unit test: Good File"
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test Good File
        uses: ./ # Uses an action in the root directory
        id: current-action
        with:
          ext: ".md"
          dir: "./test-files/good"